// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transavro/transavro.proto

package cloudwalker_srv_transavro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestSpecification struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Language             []string `protobuf:"bytes,2,rep,name=language,proto3" json:"language,omitempty"`
	Genre                []string `protobuf:"bytes,5,rep,name=genre,proto3" json:"genre,omitempty"`
	Type                 []string `protobuf:"bytes,3,rep,name=type,proto3" json:"type,omitempty"`
	Source               []string `protobuf:"bytes,4,rep,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSpecification) Reset()         { *m = RequestSpecification{} }
func (m *RequestSpecification) String() string { return proto.CompactTextString(m) }
func (*RequestSpecification) ProtoMessage()    {}
func (*RequestSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{0}
}

func (m *RequestSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpecification.Unmarshal(m, b)
}
func (m *RequestSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpecification.Marshal(b, m, deterministic)
}
func (m *RequestSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpecification.Merge(m, src)
}
func (m *RequestSpecification) XXX_Size() int {
	return xxx_messageInfo_RequestSpecification.Size(m)
}
func (m *RequestSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpecification proto.InternalMessageInfo

func (m *RequestSpecification) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *RequestSpecification) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *RequestSpecification) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *RequestSpecification) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *RequestSpecification) GetSource() []string {
	if m != nil {
		return m.Source
	}
	return nil
}

type MovieTiles struct {
	Tid                  string   `protobuf:"bytes,23,opt,name=tid,proto3" json:"tid,omitempty"`
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Poster               string   `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`
	Portrait             string   `protobuf:"bytes,3,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Background           string   `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	Rating               float64  `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Runtime              string   `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Target               []string `protobuf:"bytes,7,rep,name=target,proto3" json:"target,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Package              string   `protobuf:"bytes,9,opt,name=package,proto3" json:"package,omitempty"`
	Source               string   `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Genre                []string `protobuf:"bytes,11,rep,name=genre,proto3" json:"genre,omitempty"`
	Year                 string   `protobuf:"bytes,12,opt,name=year,proto3" json:"year,omitempty"`
	Director             []string `protobuf:"bytes,13,rep,name=director,proto3" json:"director,omitempty"`
	Cast                 []string `protobuf:"bytes,14,rep,name=cast,proto3" json:"cast,omitempty"`
	Synopsis             string   `protobuf:"bytes,15,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	TileType             string   `protobuf:"bytes,16,opt,name=tileType,proto3" json:"tileType,omitempty"`
	StartTime            float64  `protobuf:"fixed64,17,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StartIndex           float64  `protobuf:"fixed64,18,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	UseAlternate         bool     `protobuf:"varint,19,opt,name=useAlternate,proto3" json:"useAlternate,omitempty"`
	AlternateUrl         string   `protobuf:"bytes,20,opt,name=alternateUrl,proto3" json:"alternateUrl,omitempty"`
	PlaystoreUrl         string   `protobuf:"bytes,21,opt,name=playstoreUrl,proto3" json:"playstoreUrl,omitempty"`
	DetailPage           bool     `protobuf:"varint,22,opt,name=detailPage,proto3" json:"detailPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieTiles) Reset()         { *m = MovieTiles{} }
func (m *MovieTiles) String() string { return proto.CompactTextString(m) }
func (*MovieTiles) ProtoMessage()    {}
func (*MovieTiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{1}
}

func (m *MovieTiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieTiles.Unmarshal(m, b)
}
func (m *MovieTiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieTiles.Marshal(b, m, deterministic)
}
func (m *MovieTiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieTiles.Merge(m, src)
}
func (m *MovieTiles) XXX_Size() int {
	return xxx_messageInfo_MovieTiles.Size(m)
}
func (m *MovieTiles) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieTiles.DiscardUnknown(m)
}

var xxx_messageInfo_MovieTiles proto.InternalMessageInfo

func (m *MovieTiles) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *MovieTiles) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieTiles) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *MovieTiles) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *MovieTiles) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *MovieTiles) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MovieTiles) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *MovieTiles) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *MovieTiles) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MovieTiles) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *MovieTiles) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MovieTiles) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *MovieTiles) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MovieTiles) GetDirector() []string {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *MovieTiles) GetCast() []string {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *MovieTiles) GetSynopsis() string {
	if m != nil {
		return m.Synopsis
	}
	return ""
}

func (m *MovieTiles) GetTileType() string {
	if m != nil {
		return m.TileType
	}
	return ""
}

func (m *MovieTiles) GetStartTime() float64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MovieTiles) GetStartIndex() float64 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *MovieTiles) GetUseAlternate() bool {
	if m != nil {
		return m.UseAlternate
	}
	return false
}

func (m *MovieTiles) GetAlternateUrl() string {
	if m != nil {
		return m.AlternateUrl
	}
	return ""
}

func (m *MovieTiles) GetPlaystoreUrl() string {
	if m != nil {
		return m.PlaystoreUrl
	}
	return ""
}

func (m *MovieTiles) GetDetailPage() bool {
	if m != nil {
		return m.DetailPage
	}
	return false
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{5}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{7}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d341e902a3733f6, []int{8}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestSpecification)(nil), "cloudwalker.srv.transavro.RequestSpecification")
	proto.RegisterType((*MovieTiles)(nil), "cloudwalker.srv.transavro.MovieTiles")
	proto.RegisterType((*Message)(nil), "cloudwalker.srv.transavro.Message")
	proto.RegisterType((*Request)(nil), "cloudwalker.srv.transavro.Request")
	proto.RegisterType((*Response)(nil), "cloudwalker.srv.transavro.Response")
	proto.RegisterType((*StreamingRequest)(nil), "cloudwalker.srv.transavro.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "cloudwalker.srv.transavro.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "cloudwalker.srv.transavro.Ping")
	proto.RegisterType((*Pong)(nil), "cloudwalker.srv.transavro.Pong")
}

func init() { proto.RegisterFile("proto/transavro/transavro.proto", fileDescriptor_2d341e902a3733f6) }

var fileDescriptor_2d341e902a3733f6 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0x13, 0x3b,
	0x10, 0xee, 0x36, 0xff, 0x73, 0x7a, 0xce, 0x49, 0x7d, 0x72, 0x8a, 0x09, 0xa5, 0x8d, 0x16, 0x21,
	0x05, 0x81, 0xd2, 0x0a, 0x9e, 0x00, 0x71, 0x81, 0xb8, 0xa8, 0x54, 0xb6, 0xe1, 0x01, 0xdc, 0xcd,
	0x74, 0x65, 0x65, 0x63, 0x2f, 0xb6, 0x37, 0x90, 0x6b, 0x6e, 0x79, 0x5c, 0x1e, 0x00, 0x8d, 0xbd,
	0x9b, 0x6e, 0x2b, 0x1a, 0xb8, 0x9b, 0x6f, 0xe6, 0x9b, 0xf1, 0xe7, 0x6f, 0xbd, 0x03, 0xa7, 0x85,
	0xd1, 0x4e, 0x9f, 0x39, 0x23, 0x94, 0x15, 0x6b, 0xd3, 0x88, 0x66, 0xbe, 0xc2, 0x1e, 0xa7, 0xb9,
	0x2e, 0x17, 0x5f, 0x44, 0xbe, 0x44, 0x33, 0xb3, 0x66, 0x3d, 0xdb, 0x12, 0xe2, 0xef, 0x11, 0x8c,
	0x12, 0xfc, 0x5c, 0xa2, 0x75, 0x57, 0x05, 0xa6, 0xf2, 0x46, 0xa6, 0xc2, 0x49, 0xad, 0xd8, 0x11,
	0x74, 0xd7, 0xa8, 0x16, 0xda, 0xf0, 0x68, 0x12, 0x4d, 0x07, 0x49, 0x85, 0xd8, 0x18, 0xfa, 0xb9,
	0x50, 0x59, 0x29, 0x32, 0xe4, 0xfb, 0x93, 0xd6, 0x74, 0x90, 0x6c, 0x31, 0x1b, 0x41, 0x27, 0x43,
	0x65, 0x90, 0x77, 0x7c, 0x21, 0x00, 0xc6, 0xa0, 0xed, 0x36, 0x05, 0xf2, 0x96, 0x4f, 0xfa, 0x98,
	0xa6, 0x5b, 0x5d, 0x9a, 0x14, 0x79, 0xdb, 0x67, 0x2b, 0x14, 0xff, 0x68, 0x03, 0x5c, 0xe8, 0xb5,
	0xc4, 0xb9, 0xcc, 0xd1, 0xb2, 0x21, 0xb4, 0x9c, 0x5c, 0xf0, 0x47, 0x5e, 0x01, 0x85, 0x74, 0x84,
	0x93, 0x2e, 0xc7, 0x4a, 0x55, 0x00, 0x34, 0xae, 0xd0, 0xd6, 0xa1, 0xe1, 0xfb, 0x41, 0x6c, 0x40,
	0x24, 0xb6, 0xd0, 0xc6, 0x19, 0x21, 0x1d, 0x6f, 0xf9, 0xca, 0x16, 0xb3, 0x13, 0x80, 0x6b, 0x91,
	0x2e, 0x33, 0xa3, 0x4b, 0xb5, 0xe0, 0x6d, 0x5f, 0x6d, 0x64, 0x68, 0xa6, 0x11, 0x4e, 0xaa, 0x8c,
	0x77, 0x26, 0xd1, 0x34, 0x4a, 0x2a, 0xc4, 0x38, 0xf4, 0x4c, 0xa9, 0x9c, 0x5c, 0x21, 0xef, 0xfa,
	0xa6, 0x1a, 0x52, 0x87, 0x13, 0x26, 0x43, 0xc7, 0x7b, 0xe1, 0x52, 0x01, 0x6d, 0x0d, 0xe8, 0x7b,
	0x7a, 0x30, 0x80, 0x43, 0xaf, 0x10, 0xe9, 0x92, 0x5c, 0x1c, 0x84, 0x29, 0x15, 0x6c, 0x58, 0x03,
	0xe1, 0x2e, 0x01, 0xdd, 0x9a, 0xfb, 0xd7, 0x3d, 0x73, 0x37, 0x28, 0x0c, 0x3f, 0x08, 0xb3, 0x29,
	0xa6, 0x5b, 0x2f, 0xa4, 0xc1, 0xd4, 0x69, 0xc3, 0xff, 0x0e, 0x9f, 0xa8, 0xc6, 0xc4, 0x4f, 0x85,
	0x75, 0xfc, 0x9f, 0xf0, 0x31, 0x28, 0x26, 0xbe, 0xdd, 0x28, 0x5d, 0x58, 0x69, 0xf9, 0xbf, 0xc1,
	0xa5, 0x1a, 0x53, 0xcd, 0xc9, 0x1c, 0xe7, 0xa4, 0x7f, 0x18, 0x6a, 0x35, 0x66, 0xc7, 0x30, 0xb0,
	0x4e, 0x18, 0x37, 0x27, 0x2f, 0x0e, 0xbd, 0x49, 0xb7, 0x09, 0xf2, 0xd7, 0x83, 0x0f, 0x6a, 0x81,
	0x5f, 0x39, 0xf3, 0xe5, 0x46, 0x86, 0xc5, 0x70, 0x50, 0x5a, 0x7c, 0x9b, 0x3b, 0x34, 0x4a, 0x38,
	0xe4, 0xff, 0x4d, 0xa2, 0x69, 0x3f, 0xb9, 0x93, 0x23, 0x8e, 0xa8, 0xc1, 0x27, 0x93, 0xf3, 0x91,
	0x57, 0x70, 0x27, 0x47, 0x9c, 0x22, 0x17, 0x1b, 0xeb, 0xb4, 0xf1, 0x9c, 0xff, 0x03, 0xa7, 0x99,
	0x23, 0x2d, 0x0b, 0x74, 0x42, 0xe6, 0x97, 0x64, 0xf8, 0x91, 0x3f, 0xa9, 0x91, 0x89, 0x9f, 0x40,
	0xef, 0x02, 0xad, 0x25, 0xfb, 0x87, 0xd0, 0xb2, 0x62, 0x53, 0x3d, 0x2f, 0x0a, 0xe3, 0xa7, 0xd0,
	0xab, 0xfe, 0x10, 0x72, 0x4f, 0x89, 0x55, 0xfd, 0xf8, 0x7c, 0x1c, 0x1f, 0x43, 0x3f, 0x41, 0x5b,
	0x68, 0x65, 0x7d, 0xf3, 0xca, 0x66, 0x75, 0xf3, 0xca, 0x66, 0xf1, 0x14, 0x86, 0x57, 0xce, 0xa0,
	0x58, 0x49, 0x95, 0xd5, 0x53, 0x46, 0xd0, 0x49, 0x75, 0xa9, 0x9c, 0xe7, 0xb5, 0x92, 0x00, 0xe2,
	0x17, 0x70, 0xd8, 0x60, 0x56, 0x03, 0x7f, 0x4d, 0x3d, 0x81, 0xf6, 0x25, 0x3d, 0x45, 0x7a, 0x2a,
	0xce, 0xe8, 0x25, 0x56, 0xe5, 0x0a, 0xf9, 0xba, 0x7e, 0xb8, 0xfe, 0xfa, 0x5b, 0x0b, 0x06, 0xf3,
	0x7a, 0x05, 0xb0, 0x8f, 0xd0, 0x7e, 0x27, 0xf2, 0x9c, 0xc5, 0xb3, 0x07, 0xd7, 0xc4, 0xac, 0x92,
	0x3e, 0x7e, 0xb6, 0x93, 0x13, 0x44, 0xc7, 0x7b, 0x2c, 0x83, 0x6e, 0xb8, 0x0b, 0x7b, 0xb9, 0xa3,
	0xe1, 0xbe, 0x31, 0xe3, 0x57, 0x7f, 0x46, 0xae, 0x8f, 0x39, 0x8f, 0x58, 0x02, 0x7d, 0x72, 0xc2,
	0xdf, 0xf6, 0x74, 0x47, 0x37, 0x91, 0xc6, 0x3b, 0x09, 0x5a, 0x65, 0xf1, 0xde, 0x34, 0x3a, 0x8f,
	0xd8, 0x0d, 0xf4, 0xdf, 0xa3, 0x0b, 0x0b, 0xe8, 0xec, 0xf7, 0x9e, 0xdc, 0x59, 0x9b, 0xe3, 0xe7,
	0x3b, 0x1a, 0x6e, 0x17, 0x1b, 0x69, 0xbf, 0xee, 0xfa, 0xe5, 0xfc, 0xe6, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x46, 0xcc, 0xc3, 0x72, 0xbf, 0x05, 0x00, 0x00,
}
